import {
  Clock3,
  Image,
  CircleDollarSign,
  Globe,
} from "lucide-react";

const GridCardSectionData = {
  heading: "The Data Behind the Workforce Planning Imperative",

  description:
    "Research from Korn Ferry and the Korn Ferry Institute quantifies the planning gap and the cost of leaving it unaddressed.",

  items: [
    {
      icon: <Clock3 size={20} />,
      value: "35%",
      description:
        "of CHROs report future workforce needs are routinely overlooked due to short-term pressures, leaving organizations exposed when growth accelerates. (Korn Ferry)",
    },
    {
      icon: <Image size={20} />,
      value: "18%",
      description:
        "Only a small percentage of CHROs consistently use data analytics to inform people decisions—the vast majority still plan on instinct rather than evidence (Korn Ferry).",
    },
    {
      icon: <CircleDollarSign size={20} />,
      value: "2.5x",
      description:
        "Higher revenue growth is generated by organizations with high workforce engagement scores compared to lower-engagement peers—talent planning is a direct financial lever (Korn Ferry Institute).",
    },
    {
      icon: <Globe size={20} />,
      value: "66%",
      description:
        "A majority of CHROs know which skills their organization needs, but only 48% know how to acquire them—an execution gap that strategic workforce planning directly closes (Korn Ferry).",
    },
  ],
};

export default GridCardSectionData;